#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    url: "jdbc:mysql:driver://localhost:3306/test
#"
#    username: ufsmooc
#    password: '123'